# Generated by Django 4.1 on 2022-09-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField(max_length=50, null=True)),
                ('id_user', models.IntegerField(max_length=50, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('nodeid', models.TextField(max_length=50, null=True)),
            ],
        ),
    ]
