# Generated by Django 4.1 on 2022-09-21 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_datanew_delete_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datanew',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='datanew',
            name='nodeid',
        ),
        migrations.RemoveField(
            model_name='datanew',
            name='type',
        ),
    ]
