# Generated by Django 4.1 on 2022-09-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_datanew_id_user_remove_datanew_nodeid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datanew',
            name='id_user',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='datanew',
            name='nodeid',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datanew',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
